package com.demo.ordersManager.dto;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.demo.ordersManager.converter.LocalDateTimeConvertor;
import org.springframework.data.annotation.Id;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "order")
public class Order {

    @Id
    private OrderId key;
    private String organizationId;
    @DynamoDBAttribute(attributeName = "bookingStatus")
    private String bookingStatus;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return key.getId();
    }


    public void setId(String id) {
        if(key== null){
            key = new OrderId();
        }
        key.setId(id);
    }

    @DynamoDBRangeKey(attributeName = "creationDate")
    @DynamoDBTypeConverted(converter = LocalDateTimeConvertor.class)
    public LocalDateTime getCreationDate() {
        return key.getCreationDate();
    }

    public void setCreationDate(LocalDateTime creationDate) {
        if(key == null){
            key = new OrderId();
        }
        key.setCreationDate(creationDate);
    }

    public String getOrganizationId() {
        return organizationId;
    }

    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    public String getBookingStatus() {
        return bookingStatus;
    }

    public void setBookingStatus(String bookingStatus) {
        this.bookingStatus = bookingStatus;
    }
}
